
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ric.Db.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Run
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public TaskResult Result { get; set; }

    public int TaskId { get; set; }

    public int UserId { get; set; }

    public int Duration { get; set; }



    public virtual Task Task { get; set; }

    public virtual User User { get; set; }

}

}
