
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ric.Db.Model
{

using System;
    

public enum ScheduleFrequency : short
{

    Workday = 0,

    Daily = 1,

    Weekly = 2,

    Monthly = 3,

    Once = 4,

}

}
