
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ric.Db.Model
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.ManagingMarkets = new HashSet<Market>();

        this.DevTasks = new HashSet<Task>();

        this.Team = new HashSet<User>();

        this.Schedules = new HashSet<Schedule>();

        this.Runs = new HashSet<Run>();

        this.Configs = new HashSet<Config>();

    }


    public int Id { get; set; }

    public string WinUser { get; set; }

    public string GedaUser { get; set; }

    public string GedaPassword { get; set; }

    public UserGroup Group { get; set; }

    public UserStatus Status { get; set; }

    public string Email { get; set; }

    public string Surname { get; set; }

    public string Familyname { get; set; }

    public int MainMarketId { get; set; }

    public int ManagerId { get; set; }



    public virtual ICollection<Market> ManagingMarkets { get; set; }

    public virtual ICollection<Task> DevTasks { get; set; }

    public virtual Market MainMarket { get; set; }

    public virtual User Manager { get; set; }

    public virtual ICollection<User> Team { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; }

    public virtual ICollection<Run> Runs { get; set; }

    public virtual ICollection<Config> Configs { get; set; }

}

}
